#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/openbox-themes"
STYLE="tokyo"
RASI="$DIR/themes/$STYLE/rofi/style-7.rasi"

# Run
rofi \
    -show drun \
	-kb-cancel Alt-F1 \
	-theme ${RASI}
